### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by piratecarrot** [Mobject-Dev-Team/mobject-coding-convention#1]
Not sure what the thoughts are on coding style, but they should probably be addressed at some stage.

One thing I do find jarring as I have never seen it used is PascalCase method arguments. It makes it difficult to discern local variables from Properties, especially since the TwinCAT editor is so lacklustre.

Consistency with naming of `POINTER TO SomeType` and `PVOID`, should either or both have prefix of `p` or should they be suffixed with address, e.g. `SomethingAddress`.

**Comment by benhar-dev** [comment]
Hi @piratecarrot, I have added the convention which is used in mobject. 

pCount : POINTER TO INT; // this is a pointer so must have lowercase p prefix
counterAddress : PVOID; // this is an address, so good practice to add Address to the symbol
